application: gcp-jp
version: v1-6
runtime: python27
api_version: 1
threadsafe: true
skip_files: 
    - recommend/
    - tests/
    - tools/
    - ^(.*/)?.*\.py[co]$

handlers:
    - url: /.*
      script: main.app
